### PR TITLE
Fix errors when setting custom namespace

### LINKED ISSUE #428: Defining custom namespace overwrites routes.rb
When creating a super scaffold with a custom name space, rather than adding it, it rewrites the original routes.rb and only focuses on the new namespace

### PR DESCRIPTION
**Pull request by gazayas**
- Closes https://github.com/bullet-train-co/bullet_train/issues/428
- Working on closing bullet-train-co/bullet_train-core#1023

## Concerning issue 428 in the starter repo
Now that we have multiple routes files, I used `routes_path` to make sure we're writing to the correct files.

## Concerning bullet-train-co/bullet_train-core#1023
https://github.com/bullet-train-co/bullet_train-super_scaffolding/blob/9a01b0dcbf62a585f2b7ec761bffde9613c47471/lib/scaffolding/transformer.rb#L1269-L1273

We have `skip-api` set to `true` here, so we can generate the missing API controller in bullet-train-co/bullet_train-core#1023 by removing this line. I'm assuming that's what we'll want to do since we're already generating the API views when super scaffolding. Things have changed a lot since we stopped using Grape, so I can see us removing the flag here.

Concerning the missing show page, here's the block that tries to add a child to the parent's show page:
https://github.com/bullet-train-co/bullet_train-super_scaffolding/blob/9a01b0dcbf62a585f2b7ec761bffde9613c47471/lib/scaffolding/transformer.rb#L1343-L1351

In bullet-train-co/bullet_train-core#1023's case, the child is `Job`. However, the string is getting transformed in such a way that the parent `Team` is getting namespaced under the custom namespace `client`:
`'./app/views/client/teams/show.html.erb'`

Since the namespace `client` doesn't have its own set of views, do we need to add a list of the children to the `Team` show page, or can we just skip this part? I'm guessing that we <i>should</i> add it, so I'll try to set this PR as ready for review once I get that set up.

## Tests
I don't think we have any tests in place for the namespace option, so I'll keep that on my radar as I work through this one.

### CODE REVIEW

**Comment by gazayas** [comment]
It looks like we're not creating the `.app/controllers/api/v1/#{child}_controller.rb` when super scaffolding a new model, regardless if we're using a custom namespace or not. I'll try to find a good place to create the file.

**Comment by gazayas** [comment]
@andrewculver As I'm sifting through this one, I feel like there's a lot of moving parts and I want to make sure I'm headed in the right direction. In other words, I guess I don't have a clear goal in sight as to how these namespaced files need to be set up, and I don't want to start building too much in the wrong direction.

## Controller placement
For example, one thing that stands out is the directory hierarchy for the normal child controller. It is namespaced under `client`, as expected:
`app/controllers/client/jobs_controller.rb`.

However the API controller is here, not under `client`:
`app/controllers/api/v1/jobs_controller.rb`

I'm guessing that we need to create the `client` directory and put the controller in there.

## Routes files
When setting `client` as a custom namespace, we add a new file `client.rb` and use `draw` to include it in the original routes file. However, we don't do anything like this with the API routes file. Should we add a new hierarchy per version which the main API routes file includes using `draw` as well? For example:
```
config/
  routes/
    api/
      v1/
        v1.rb
        client.rb
    client.rb
    concerns.rb
    devise.rb
    sidekiq.rb
  routes.rb
```

## Other files
I think I'll wait until we have a clear direction on this part, because I don't want to take up too much time if it's not what we need.

As far as my analysis of the issue goes though, it seems like these are the main things we need to take care of.

**Comment by gazayas** [comment]
With this last commit, I made sure we're including the custom namespaced routes file (`config/routes/client.rb`) in our main routes file, because it wasn't being included using `draw`.

Now that I'm looking over the code, it seems like everything isn't set in place yet (for example, `code_for_child_on_parent_show_page` which I brought up in the first comment is an empty method added recently in https://github.com/bullet-train-co/bullet_train-super_scaffolding/commit/f46d36b87397142d3fd7537134e7cfa02c6cdae8), so I think I'll cut the PR here.

I could see us doing the following things next:
1. Editing paths in the API controller test code to reflect the custom namespaces.
2. Editing Super Scaffolded controller names to use the correct namespaces.
3. Adding the API routes hierarchy that I mentioned in the previous comment.
etc...

I'll leave things as is for now since I'm noticing some other TODOs in the Transformer that I overlooked before.

**Comment by andrewculver** [comment]
@gazayas Can you resolve the conflicts on this one?

**Comment by gazayas** [comment]
Closing in favor of https://github.com/bullet-train-co/bullet_train-core/pull/35

**Pull request closed without merging**
