### PR TITLE
Introduce `FileManipulator`

### PR DESCRIPTION
**Pull request by gazayas**
This has been on my radar for a while and I think there's a lot of work that can be done here. My idea is to have the following design. Half of these are already in place, I just want to reiterate the information here for clarity:
## Generic Manipulators
1. `FileManipulator`: A module that takes care of basic file manipulation.
2. `BlockManipulator`: A module that takes care of basic block manipulation.

If we can extract these into a cohesive system that works well together, I think this could be extracted into its own package.

## Super Scaffolding Manipulators
1. `RoutesFileManipulator`: A class which includes `FileManipulator`/`BlockManipulator` and handles the routes file when Super Scaffolding.
2. `SuperScaffoldingFileManipulator`: A class scoped to the specific needs of Super Scaffolding. Basically, this class is for anything minor enough that doesn't need its own class like the `RoutesFileManipulator` does, but still unique enough to put in the context of Super Scaffolding. Also includes `FileManipulator` and `BlockManipulator`.

## Keeping track of lines
I wrote this in #32:
> Although I wrote lines in the arguments, I don't like the idea of passing lines each time from an external object (I considered using ObjectSpace.id2ref(lines.id) so we only handle one object in memory, but it's tricky because lines is an array). Since the BlockManipulator and RoutesFileManipulator each have their own lines object, they begin to differ once we start to edit them, so I ended up passing lines here just so we're always dealing with the same set of lines.

The methods I extracted in this PR here already reflect that kind of thinking, so it was easy to implement. However, I'm not sure if this is the best design, and I'm not sure exactly what design pattern `FileManipulator` and `BlockManipulator` might fall under, but I'm writing them as modules specifically for this reason (although I initially considered making them classes and just having `RoutesFileManipulator` etc. inherit them). I'd love to hear some feedback as far as design goes with these two abstractions, but I'm leaning on the side of making them modules that rely heavily on `self` methods.

### CODE REVIEW

**Comment by gazayas** [comment]
Forgot to mention, but we would make distinctions between what should stay in the Transformer and what should go in the `SuperScaffoldingFileManipulator`. For example, `add_additional_step` would simply stay in the Transformer.

**Comment by gazayas** [comment]
`RoutesFileManipulator#insert` takes an Array, whereas `BlockManipulator#insert` takes a String for the values we want to insert. I think it would be better to have `insert` take an Array so I want the change the `BlockManipulator` method so that it does. I think that in itself will take some time, so I might cut the PR after that and then continue working on refactoring other related places in another PR after this one's out of the way.

**Comment by gazayas** [comment]
I'm going to cut the PR here because I think extracting the following methods from the `RoutesFileManipulator` to the `BlockManipulator` is going to be a lot harder than expected. We have the following methods in the `RoutesFileManipulator`:
1. `insert`
2. `insert_before`
3. `insert_after`

However, the `BlockManipulator` just has `insert` which accepts keywords for `before` and `after`, and like I mentioned in the previous comment, the arguments are different data types.

Also, the `RoutesFileManipulator` tends to handle line numbers often, whereas the `BlockManipulator` handles the lines themselves. Besides that, there are also some little things like adding an extra line if the last line WITHIN a block is `end`, etc. I managed to get some parts working, but the system tests were failing and because of the little details that would need to go into the refactor, I'd just rather deal with that in a PR of its own.

**Comment by andrewculver** [comment]
@gazayas Thanks for taking the initiative on this one!

**Comment by gazayas** [comment]
@andrewculver Sure thing! I'm still somewhat intimidated by the thought of refactoring the `RoutesFileManipulator` with the `BlockManipulator`, but I'll keep it in the back of my mind for later...

**Pull request merged**
