### PR TITLE
Create a `super_scaffold` command, provided by the gem

### PR DESCRIPTION
**Pull request by indirect**
It doesn't fully generate crud models (seems like some test templates are missing?), but it gets a lot farther than before.

```
❯ bundle exec super_scaffold crud Trip Account name:string
Writing './app/controllers/account/trips_controller.rb'.
Fixing Standard Ruby on './app/controllers/account/trips_controller.rb'.
The directory ./app/views/account/trips already exists, skipping generation.
Writing './app/views/account/trips/index.html.erb'.
Writing './app/views/account/trips/_menu_item.html.erb'.
Writing './app/views/account/trips/_index.html.erb'.
Writing './app/views/account/trips/_trip.json.jbuilder'.
Writing './app/views/account/trips/index.json.jbuilder'.
Writing './app/views/account/trips/show.json.jbuilder'.
Writing './app/views/account/trips/edit.html.erb'.
Writing './app/views/account/trips/show.html.erb'.
Writing './app/views/account/trips/_form.html.erb'.
Writing './app/views/account/trips/new.html.erb'.
Writing './app/views/account/trips/_breadcrumbs.html.erb'.
Writing './config/locales/en/trips.en.yml'.
Writing './app/controllers/api/v1/trips_endpoint.rb'.
Fixing Standard Ruby on './app/controllers/api/v1/trips_endpoint.rb'.
/Users/andre/src/bullet-train-co/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb:119:in `resolve_template_path': Couldn't find the Super Scaffolding template for `./test/controllers/api/v1/scaffolding/completely_concrete/tangible_things_endpoint_test.rb` in any of the following locations: (RuntimeError)

/Users/andre/src/bullet-train-co/bullet_train-super_scaffolding
        from /Users/andre/src/bullet-train-co/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb:1191:in `block in scaffold_crud'
        from /Users/andre/src/bullet-train-co/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb:1190:in `each'
        from /Users/andre/src/bullet-train-co/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb:1190:in `scaffold_crud'
        from /Users/andre/src/bullet-train-co/bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/crud_scaffolder.rb:51:in `run'
        from /Users/andre/src/bullet-train-co/bullet_train-super_scaffolding/lib/scaffolding/script.rb:99:in `<top (required)>'
        from /Users/andre/src/bullet-train-co/bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding.rb:27:in `require'
        from /Users/andre/src/bullet-train-co/bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding.rb:27:in `run'
        from /Users/andre/src/bullet-train-co/bullet_train-super_scaffolding/exe/super_scaffold:3:in `<top (required)>'
        from bin/super_scaffold:29:in `load'
        from bin/super_scaffold:29:in `<main>'
```

### CODE REVIEW

**Comment by andrewculver** [comment]
@indirect I like this a lot more than requiring a `bin/super-scaffold` binstub. My guess is that this'll be working a lot better now than it was back when you first got started, just because of all the work we've done since. Going to assign this to @gazayas and have him take it over the finish line.

**Comment by andrewculver** [comment]
It does make me wonder whether we should actually introduce a `bt` command, though, and just have `super_scaffold` be one option for it. 🤔

**Comment by indirect** [comment]
I think that’s a fantastic idea. I’d do it the way Bundler offers pluggable sub commands, which is also like git: if you run `bt super_scaffold` the bt command tries to run `bt-super_scaffold`, which could be provided by this gem.

**Comment by andrewculver** [comment]
Great insight. That sounds perfect. Indebted, @indirect!

**Comment by gazayas** [comment]
@indirect This is an awesome idea, I'll look over the code and see what I can do :raised_hands:

**Comment by andrewculver** [comment]
Continued in https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/41.

**Pull request closed without merging**
